server:
  port: 8080

spring:
  application:
    name: community

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB      # 单个文件最大大小 (按需调整，例如 10MB, 50MB)
      max-request-size: 50MB   # 整个请求最大大小 (通常比单个文件大，用于多文件上传)

  # 1. ????? (?? url ????????? password)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: yangyiming.com
  # 2. Redis ??
  data:
    redis:
      host: localhost
      port: 6379
      password: yangyiming.com
      database: 0

  # 3. RabbitMQ ??
  rabbitmq:
    host: localhost
    port: 5672
    username: zongzuo
    password: yangyiming.com

  # 4. ???? (SMTP) - ????????????????????????????????
  mail:
    host: smtp.163.com
    username: metrocommunity@163.com # ?????
    password: GTg3F34BVVjFK4XB    # ?????
    default-encoding: UTF-8
    debug: true

# MyBatis-Plus ??
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # ??????? SQL?????
  global-config:
    db-config:
      logic-delete-field: deleted # ???????
      logic-delete-value: 1
      logic-not-delete-value: 0

aliyun:
  oss:
    endpoint: oss-cn-shanghai.aliyuncs.com  # 换成你的地域节点
    access-key-id: ${OSS_ACCESS_KEY_ID:default_id}          # 换成你的 Key ID
    access-key-secret: ${OSS_ACCESS_KEY_SECRET:default_secret}      # 换成你的 Key Secret
    bucket-name: metro-community